Implementing a configurable read validation system that defaults to skipping validation
This commit represents an incomplete solution to [issue
#47](https://github.com/noamteyssier/paraseq/issues/47), which flagged
the fact that FASTQ-derived paired reads are as-yet unvalidated in
paraseq. The solution centers around a `ValidationMode` enum in the new
validation module, which contains `ValidationMode`, trait impls and some
helpful inherent methods on `ValidationMode`, an error submodule
containing a `ValidationError` enum, and tests.

`ValidationMode` has three unit variants representing three levels of
validation, which should be self-explanatory:

```rust
#[derive(Debug, Default, Clone, Copy)]
pub enum ValidationMode {
    #[default]
    Skip,
    Normal,
    Strict,
}
```

To make it easier to generate the enum from command line args, I’ve
implemented `FromStr` on it, and for kicks you can convert it from a
bool as well. It also implements `Copy` so that its value semantics
reflect that it’s less expensive to copy than it is to take a reference.

The enum currently carries a couple of pre-implemented validation
methods: one for checking that putatively paired reads contain `/1` and
`/2` suffixes, and one for checking that read identifiers are the same,
irrespective of those suffixes. However, I also gave it methods that
allow users to apply their own validation logic as a closure—“bring your
own validation!”

The part that remains, should we wish to complete this PR, is how to
pass the chosen mode anywhere in the callstack where it may be needed,
and how to expose it to the user for configuration. Ideally, we could do
so without virally spreading the necessity of a new function argument,
and also without any breaking changes.

With the setup described above, I can foresee at least a couple paths
for integration.

#### 1) Expose via `GenericReader` and any types that impl it

In this path, we modify the trait `GenericReader` to provider a getter
and a setter for the validation mode:

```rust
pub trait GenericReader: Send {
    ...

    fn validation_mode(&self) -> ValidationMode {
        ValidationMode::default()
    }

    fn set_validation_mode(&mut self, _mode: ValidationMode) {
        // Default no-op for types that don't support it
        // Implementors override this
    }

    ...
}
```

And then, we implement a new private field to store the validation mode,
e.g., for `fastq::Reader`:

```rust
pub struct Reader<R: io::Read> {
    reader: R,
    overflow: Vec<u8>,
    eof: bool,
    batch_size: Option<usize>,
    validation_mode: ValidationMode // <- NEW
}

impl<R: io::Read> Reader<R> {
    pub fn new(reader: R) -> Self {
        Self {
            overflow: Vec::with_capacity(1024),
            reader,
            eof: false,
            batch_size: None,
            validation_mode: ValidationMode::default() // <- NEW
        }
    }
}
```

I’d probably also want to bring it in with your builder-pattern-ish API
and add `.with_validation_mode()` as an interent method for types that
are `GenericReader`.

This pathway has a couple of downsides:
1. Giving `.validation_mode()` a default impl to avoid breaking changes
comes with a footgun: it will always return `ValidationMode::Skip`
unless the user remembers to override the default `.validation_mode()`
impl, which isn’t great.
2. If there’s more than one instance of types that are `GenericReader`,
each will have its own mode setting, which introduces the need some
method for forming a consensus. I’d do strictest-wins here, but this
still introduces more machinery.

That said, this may be the best way to expose the validation API for any
and all collections of records as opposed to the following pathway. It
also puts validation mode alongside other lower-level reader settings
like batch size. Plus, maybe it would be interesting to allow different
validation strictnesses for reads from different circumstances?

#### 2) Expose via `MTGenericReader` and any types that impl it

It may instead make more sense to put an equivalent to the above getter
and setter onto the slightly higher-level `MTGenericReader`, with the
same builder-ish inherent methods for any types that impl it. Also like
with the `GenericReader` pathway, this would require a new private field
in the concrete reader types, e.g.:

```rust
struct SingleReader<R: GenericReader> {
    reader: Mutex<R>,
    validation_mode: ValidationMode, // <- NEW
}

impl<R: GenericReader> SingleReader<R> {
    pub fn new(reader1: R) -> Self {
        SingleReader {
            reader: Mutex::new(reader1),
            validation_mode: ValidationMode, // <- NEW
        }
    }
}
```

This approach also means we don’t need to implement validation mode
consensus machinery, and it matches the level of abstraction where
`.check_read_pair()` is called to boot:

```rust
impl<R: GenericReader> MTGenericReader for InterleavedPairedReader<R>
where
    ProcessError: From<R::Error>,
{
    ...

    fn iter(
        record_set: &Self::RecordSet,
    ) -> impl ExactSizeIterator<Item =
std::result::Result<Self::RefRecord<'_>, Self::Error>> {
        let it = R::iter(record_set);

        if it.len() % 2 != 0 {
            let error_iter =

std::iter::once(Err(ProcessError::IncompatibleInterleavedSetSize(it.len())));
            return either::Either::Left(error_iter);
        }

        let tuple_iter = it.tuples().map(|(r1, r2)| {
            let r1 = r1?;
            let r2 = r2?;

            R::check_read_pair(&r1, &r2, mode)?; // <- INTERNALLY CALLS
VALIDATION MODE GETTER
            std::result::Result::Ok((r1, r2))
        });
        either::Either::Right(tuple_iter)
    }
}

```

This is one of those weird cases where I recognize that this is the
better option, but for reasons I can’t put my finger on, I find myself
preferring the first option.

There is one more option I can think of, though!

#### 3) Leave it out of the traits and just reference validation mode
with inherent methods on the reader types

I like this option least, so I won’t spend too much time on it.
Basically, this would just mean we couldn’t make generic default impls
for methods like `.iter()` on `MTGenericReader`, which you already don’t
do. In that case, if we put a validation mode field onto the reader
types and gave them inherent getter and setter methods, accessing  the
validation mode would have to look like this:

```rust
impl<R: GenericReader> MTGenericReader for InterleavedPairedReader<R>
where
    ProcessError: From<R::Error>,
{
    ...

    fn iter(
        record_set: &Self::RecordSet,
    ) -> impl ExactSizeIterator<Item =
std::result::Result<Self::RefRecord<'_>, Self::Error>> {
        let it = R::iter(record_set);

        if it.len() % 2 != 0 {
            let error_iter =

std::iter::once(Err(ProcessError::IncompatibleInterleavedSetSize(it.len())));
            return either::Either::Left(error_iter);
        }

        let tuple_iter = it.tuples().map(|(r1, r2)| {
            let r1 = r1?;
            let r2 = r2?;

            let mode = self.validation_mode; // <- NEW. Could also be
`self.get_validation_mode()` if that's implemented as an inherent method
on `InterleavedPairedReader`
            R::check_read_pair(&r1, &r2, mode)?; // <- check_read_pair
would have to accept the validation mode as its third arg
            std::result::Result::Ok((r1, r2))
        });
        either::Either::Right(tuple_iter)
    }
}
```